In [20]:
import torch
import pandas as pd

In [5]:
x = torch.arange(12)
x_matrix = x.reshape(3,4)

In [8]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [6]:
x_matrix.shape

torch.Size([3, 4])

In [7]:
x_matrix

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
y = torch.randn(3,4) # Standard Gaussian distribution

In [16]:
y + x_matrix, y - x_matrix # Display them at the same time

(tensor([[1.4369, 0.8915, 0.5464, 1.2873],
         [1.9341, 5.0085, 6.8923, 7.5462],
         [8.0169, 8.4241, 9.8938, 9.2173]]),
 tensor([[  1.4369,  -1.1085,  -3.4536,  -4.7127],
         [ -6.0659,  -4.9915,  -5.1077,  -6.4538],
         [ -7.9831,  -9.5759, -10.1062, -12.7827]]))

In [17]:
x_matrix, y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 1.4369, -0.1085, -1.4536, -1.7127],
         [-2.0659,  0.0085,  0.8923,  0.5462],
         [ 0.0169, -0.5759, -0.1062, -1.7827]]))

In [19]:
torch.cat((x_matrix, y), dim=0), torch.cat((x_matrix, y), dim=1)

(tensor([[ 0.0000e+00,  1.0000e+00,  2.0000e+00,  3.0000e+00],
         [ 4.0000e+00,  5.0000e+00,  6.0000e+00,  7.0000e+00],
         [ 8.0000e+00,  9.0000e+00,  1.0000e+01,  1.1000e+01],
         [ 1.4369e+00, -1.0848e-01, -1.4536e+00, -1.7127e+00],
         [-2.0659e+00,  8.5384e-03,  8.9233e-01,  5.4618e-01],
         [ 1.6853e-02, -5.7591e-01, -1.0621e-01, -1.7827e+00]]),
 tensor([[ 0.0000e+00,  1.0000e+00,  2.0000e+00,  3.0000e+00,  1.4369e+00,
          -1.0848e-01, -1.4536e+00, -1.7127e+00],
         [ 4.0000e+00,  5.0000e+00,  6.0000e+00,  7.0000e+00, -2.0659e+00,
           8.5384e-03,  8.9233e-01,  5.4618e-01],
         [ 8.0000e+00,  9.0000e+00,  1.0000e+01,  1.1000e+01,  1.6853e-02,
          -5.7591e-01, -1.0621e-01, -1.7827e+00]]))

In [21]:
import os

In [22]:
os.makedirs(os.path.join('..','data'), exist_ok=True) # make new directory
data_file = os.path.join('..','data', 'house_tiny.csv') # return string, containing the file address

In [23]:
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column name
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000')

In [24]:
data = pd.read_csv(data_file)

In [26]:
data_file

'../data/house_tiny.csv'