In [1]:
import torch

In [5]:
x = torch.arange(12)
x_matrix = x.reshape(3,4)

In [8]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [6]:
x_matrix.shape

torch.Size([3, 4])

In [7]:
x_matrix

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.randn(2,3,4) # Standard Gaussian distribution

tensor([[[-0.0803, -0.1223, -1.9293,  0.0580],
         [-0.2298,  0.0931, -0.3953,  1.3276],
         [-0.6940,  1.3676, -0.2717, -0.1003]],

        [[ 0.4599,  0.2753,  0.0869, -1.4929],
         [-1.1339,  1.7273,  0.7128,  0.4061],
         [-0.7723, -0.6226,  1.6115, -0.9766]]])